/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "error": { "creationFunction": "CreateText", "text": "Something's broken.\n\nAre you online?\n\nIf you are, double check the link on the back. Thanks!" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "iSeptaLabel": { "creationFunction": "CreateText", "text": "iSepta" },
    "iSeptaUrlLabel": { "creationFunction": "CreateText", "text": "Go get an iSepta - Trains page and \nput it here ⤵" },
    "iSeptaUrlLabel1": { "creationFunction": "CreateText", "text": "Name the train, if you want" },
    "label": { "creationFunction": "CreateText", "text": "Item" },
    "list": { "creationFunction": "CreateList", "dataArray": ["Item 3"], "labelElementId": "label", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 1, "useDataSource": true },
    "nextTrainLabel": { "creationFunction": "CreateText", "text": "Loading…" },
    "poweredByLabel": { "creationFunction": "CreateText", "text": "Powered by" },
    "text": { "creationFunction": "CreateText", "text": "widget by Mat Schaffer" }
};
